In [2]:
import numpy as np
# Numpy is a foundation of the Python machine learning Stack.
# NumPy allows for efficient operations on the data structures
# often used in machine learning.

## 1. Create Vector

NumPy's main data structure is the mulidimentional array. to create a vector we simply create a one-dimentional array.

In [3]:
# Create a vector as a row
np.array([1,2,3])

array([1, 2, 3])

In [4]:
# Create a vector as a column
np.array([ [1],
           [2],
           [3] ])

array([[1],
       [2],
       [3]])

## 2.Creating a Matrix

To create a matrix we can use a Numpy two-dimentional array

In [5]:
# create a matrix with standard data structure [numpy array]
np.array([ [1,2],
           [3,4],
           [5,6] ])

array([[1, 2],
       [3, 4],
       [5, 6]])

In [6]:
# create a matrix with dedicated matrix data structure [Not Recommended]
np.mat([ [1,2],
         [3,4],
         [5,6] ])

# But Matrix data structure not recommended for two reasons
# 1. Array is the standard data structure of numpy
# 2. The Vast Majority of Numpy operation return array, not matrix object.

matrix([[1, 2],
        [3, 4],
        [5, 6]])

## 3. Create a Sparse Matrix

In [9]:
# sparse matrix only store nonzero elements and assume all other values will be zero.
# leading to significant computational saving.

# create a normal matrix with zero values
matrix = np.array([ [0, 0], [0, 1], [3, 0] ])
print("matrix\n", matrix)

# create a compressed sparse row (CSR) matrix

from scipy import sparse

matrix_sparse = sparse.csr_matrix(matrix)
print("\n\nsparse matrix\n", matrix_sparse)

# There are many different types of sparse matrices:
# 1. Compressed Sparse row (which we use).
# 2. Compressed Sparse column.
# 3. List of lists.
# 4. Dictionary of keys.

matrix
 [[0 0]
 [0 1]
 [3 0]]


sparse matrix
   (1, 1)	1
  (2, 0)	3


## 4. Selecting Elements

In [10]:
# we need to select one or more elements in a vector or matrix
vector = np.array([1, 2, 3, 4, 5, 6])
matrix = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])

# Like most things in Pyhton, NumPy arrays are zero_indexed, mean that the 
# index of the first element is 0, not 1.

In [11]:
# Vector - Select one element
print(vector[2]) # third element

# Matrix - Select one element
print(matrix[1,1]) # second row, second column.

3
5


In [12]:
# Vector - Select all elements
vector[:]

array([1, 2, 3, 4, 5, 6])

In [13]:
# Vector - Select every thing up and including the third element.
vector[:3] # note that start index [0] and last index is [2]

array([1, 2, 3])

In [14]:
# Vector - Select every thing after the third element
vector[3:]

array([4, 5, 6])

In [15]:
# Vector - Select the last element
vector[-1]

6

In [16]:
# Matrix - Select the first two row and all column
matrix[:2, :]

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
# Matrix - Select all row and the second column
matrix[:, 1:2]

array([[2],
       [5],
       [8]])

## 5. Describing a Matrix

In [19]:
# we want to describe the shape, size, and dimensions of the matrix.

# View number of rows and columns
matrix.shape

(3, 3)

In [20]:
# View number of elements (rows * columns)
matrix.size

9

In [21]:
# View number of dimensions
matrix.ndim

2

## 6. Applying Operations to Elements

In [22]:
# we want to apply some functions to multiple elements in arrays
# using numpy's vectorize

# create matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [23]:
# create function that adds 100 to something
add_100 = lambda i: i + 100

In [24]:
# create vectorized function
vectorized_add_100 = np.vectorize(add_100)

# Numpy's vectorize class convert a function into a function that can apply
# to all elements in an array.
# It's worth noting that vectorize is essentially a for loop over the element
# and does not increase performance.

In [25]:
# apply function to all element in matrix
vectorized_add_100(matrix)

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

In [26]:
# Furthermore Numpy array allow us to perform operations between arrays even
# if there dimentions are not the same. (a process called broadcasting)

# Add 100 to all element with more effecient way
matrix + 100

array([[101, 102, 103],
       [104, 105, 106],
       [107, 108, 109]])

## 7. Finding the Maximum and Minimum value

In [27]:
# we want to find the min, and max value in an array.
# using numpy's min, max methods.

matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [28]:
np.max(matrix)

9

In [29]:
np.min(matrix)

1

In [30]:
# Using the axis parameter we can also apply operation along a certain axis

# Find Max element in each column
np.max(matrix, axis=0)

array([7, 8, 9])

In [31]:
# Find Max element in each row
np.max(matrix, axis=1)

array([3, 6, 9])

## 8. Calc the Average, Variance, and Standard Deviation

In [32]:
# we want to calculate some descriptive statistics about an array

# calculate the mean
np.mean(matrix)

5.0

In [33]:
# calculate the varaince
np.var(matrix)

6.666666666666667

In [34]:
# calculate the standard deviation
np.std(matrix)

2.581988897471611

In [35]:
# Just Like the min, max we can easily get descriptive statistics about the whole 
# matrix, or do a calculation along a single axis

# Find the mean value in each column
np.mean(matrix, axis=0)

array([4., 5., 6.])

In [36]:
# Find the mean value in each row
np.mean(matrix, axis=1)

array([2., 5., 8.])

## 9. Reshaping Array

In [38]:
# we want to change the shape (number of rows and columns) of an array without changing
# the element values. Using numpy's reshape

# reshape allow us to restructure an array so that we maintain the same data
# but it is organized as a different number of rows and columns.

# the only requirement is that the shape of the original and the new matrix contain the
# same number of elements. (the same size)

# create 4x3 matrix
matrix = np.array([[1,2,3],
                   [4,5,6],
                   [7,8,9],
                   [10,11,12]])
matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [39]:
# reshape matrix into 2 x 6 matrix
matrix.reshape(2, 6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [40]:
# one useful argument in reshape is -1, which mean "as many as needed"
# so reshape(-1, 1) one column and as many rows as needed
# reshape(1, -1) one row and as many columns as needed.
matrix.reshape(-1, 1)

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12]])

In [41]:
matrix.reshape(1, -1)

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12]])

In [44]:
# if we provide one integer, reshape will return a 1D array of that length.
matrix.reshape(matrix.size) # 12

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

## 10. Transposing a Vector or Matrix

In [45]:
# transpose the vector or matrix using the T method.

matrix

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [46]:
matrix.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [47]:
# Note that the vector cannot be transposed because it is just a collection of vaules
np.array([1,2,3]).T

array([1, 2, 3])

In [48]:
# but can transpose a row vector to column vector
np.array([[1,2,3]]).T

array([[1],
       [2],
       [3]])

In [49]:
# we can do the same with reshape method
np.array([[1,2,3]]).reshape(-1, 1)

array([[1],
       [2],
       [3]])

## 11. Flattening a Matrix

In [50]:
# we need to transform a matrix to one-dimentional array using flatten

matrix = np.array([[1,2,3], [4,5,6], [7,8,9]])
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [51]:
matrix.flatten()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
# also we can use reshape method to create a row vector
matrix

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [53]:
matrix.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])

## 12. Finding the Rank of matrix

In [61]:
# the rank of matrix is the dimensions of the vector space spanned by its columns or rows.
matrix = np.array([[1,1,1],
                   [1,1,10],
                   [1,1,15]])
matrix

array([[ 1,  1,  1],
       [ 1,  1, 10],
       [ 1,  1, 15]])

In [62]:
np.linalg.matrix_rank(matrix)

2

## 13. Calculating the Determinant

In [64]:
# we need to know the determinant of a matrix
matrix = np.array([[1,2,3],[2,4,6],[3,8,9]])
np.linalg.det(matrix)

0.0

## 14. Getting the Diagonal of a matrix

In [66]:
# we need to get the diagonal elements of matrix.
matrix = np.array([[1,2,3],
                   [2,8,4],
                   [4,5,6]])
matrix.diagonal()

array([1, 8, 6])

In [69]:
matrix.diagonal(offset=-1)

array([2, 5])

## 15.Calculating the Trace of Matrix

In [70]:
# The trace of a matrix is the sum of the diagonal elements and is often
# used under the hood in machine learning methods

matrix

array([[1, 2, 3],
       [2, 8, 4],
       [4, 5, 6]])

In [71]:
matrix.trace()

15

In [72]:
# We can also return the diagonal of a matrix and calculate its sum
sum(matrix.diagonal())

15

## 16. Calculating Eignvalues and Eignvectors

In [73]:
# we need to find the eignvalues and eignvectors of square matrix
## Eigenvectors are widely used in machine learning libraries. Intuitively,
## given a linear transformation represented by a matrix, A,
## eigenvectors are vectors that, when that transformation is applied,
## change only in scale (not direction).


# create matrix
matrix = np.array([[1, -1, 3], [1, 1, 6], [3, 8, 9]])
matrix

array([[ 1, -1,  3],
       [ 1,  1,  6],
       [ 3,  8,  9]])

In [74]:
# NumPy’s linear algebra toolset, eig lets us calculate the eigenvalues,
# and eigenvectors of any square matrix.
eignvalues, eignvectors = np.linalg.eig(matrix)

In [75]:
# View eigenvalues
eignvalues

array([13.55075847,  0.74003145, -3.29078992])

In [76]:
# View eigenvectors
eignvectors

array([[-0.17622017, -0.96677403, -0.53373322],
       [-0.435951  ,  0.2053623 , -0.64324848],
       [-0.88254925,  0.15223105,  0.54896288]])

## 17. Calculate Dote Products

In [78]:
# we need to calculate the dot product of two vector
vector_a = np.array([1, 2, 3])
vector_b = np.array([5, 6, 7])

np.dot(vector_a, vector_b)

38

## 18. Adding and Subtracting Matrices

In [80]:
# we want to add or subtract two matrices

# create matrix a
matrix_a = np.array([[1,2,3], [4,5,6], [7,8,9]])
# create matrix b
matrix_b = np.array([[9,8,7],[6,5,4],[3,2,1]])
# add two matrix
print(np.add(matrix_a, matrix_b))
print("----------------")
# subtract two matrix
print(np.subtract(matrix_a, matrix_b))

[[10 10 10]
 [10 10 10]
 [10 10 10]]
----------------
[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [81]:
# or we can adding two matrix directly with + operator
matrix_a + matrix_b

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [82]:
# also subtract with - operator
matrix_a - matrix_b

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

## 19. Multiplying Matrices

In [86]:
matrix_a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [87]:
matrix_b

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [83]:
# we want to multiply two matrices.
np.dot(matrix_a, matrix_b)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [84]:
# Alternatively, in Python 3.5+ we can use the @ operator
matrix_a @ matrix_b

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [85]:
# If we want to do element-wise multiplication, we can use the * operator
matrix_a * matrix_b

array([[ 9, 16, 21],
       [24, 25, 24],
       [21, 16,  9]])

## 20. Inversing a Matrix

In [89]:
# we want to calculate the inverse of the square matrix

# create matrix
matrix = np.array([[1, 4],
                   [2, 5]])
matrix

array([[1, 4],
       [2, 5]])

In [90]:
# Calculate inverse of matrix
np.linalg.inv(matrix)

array([[-1.66666667,  1.33333333],
       [ 0.66666667, -0.33333333]])

In [91]:
# we know that matrix A multiply inv(A) equal the identity matrix
matrix @ np.linalg.inv(matrix)

array([[1., 0.],
       [0., 1.]])

## 21. Generating Random Values

In [92]:
# we want to generate pseudorandom values.

# Set seed
# it can sometimes be useful to return the same random numbers multiple
# times to get predictable, repeatable results.
# We can do this by setting the “seed”
np.random.seed(0)

In [93]:
# Generate three random floate between 0.0 and 1.0
np.random.random(3)

array([0.5488135 , 0.71518937, 0.60276338])

In [94]:
# Generate three random integers between 1 and 10
np.random.randint(1, 11, 3)

array([ 4,  8, 10])

In [95]:
# Alternatively, we can generate numbers by drawing them from a distribution
# Draw three numbers from a normal distribution with mean 0.0
# and standard deviation of 1.0
np.random.normal(0.0, 1.0, 3)

array([-1.42232584,  1.52006949, -0.29139398])

In [96]:
# Draw three numbers from a logistic distribution with mean 0.0 and scale of 1.0
np.random.logistic(0.0, 1.0, 3)

array([-0.98118713, -0.08939902,  1.46416405])

In [97]:
# Draw three numbers greater than or equal to 1.0 and less than 2.0
np.random.uniform(1.0, 2.0, 3)

array([1.47997717, 1.3927848 , 1.83607876])